[build]
  # Directory with the static files to deploy
  publish = "client"
  
  # Build command (not needed for static files, but required field)
  command = "echo 'No build step needed for static files'"

[build.environment]
  # Set any environment variables if needed
  
[[redirects]]
  # Handle client-side routing (if using SPA routing)
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optional: Set custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

